### ISSUE TITLE
Write documentation

### ISSUE THREAD

**Issue by flyingrub** [flyingrub/FFGL-plugin-quickstart#1]
- [x] Where to download MSVC / XCODE
- [x] How to create a new project
- [x] How to build a project
- [x] Get Resolume to recognise it
---
- [ ] How does the api works 
- [x] How to create a simple plugin from scratch
- [ ] Versioning
- [ ] Params ?
- [ ] How to access features that are now "hidden" to keep it as simple as possible
---
- [x] Write API docs

**Comment by spxl** [comment]
Can you please explain why all Param storage and methods use "Ptr" objects (std::shared_ptr objects)?

It seems to me that the params/options should always be held/owned in the protected "params" vector.

**Comment by flyingrub** [comment]
I decided to use a pointer to be able to use Polymorphism, and have different behaviour for different kind of params. I just used `shared_ptr` for now to quickly iterate but it's true that we could make `params` to own them.
